Upgrade to Django 2 (#42)
* Upgrade to Django==2.0.13

* Add missing ON DELETE CASCADE to old migrations

* Upgrade to Django==2.2.17

Hoping to solve string type problem, in case related to python 3.9

* Replace auth_views.login/logout with auth_views.LoginView/LogoutView

* %s/MIDDLEWARE_CLASSES/MIDDLEWARE

* Update to default Django 2.2 middleware

* Resolve TypeError by removing byte qualifier in M2M fields in migrations

Was getting this error when trying to run migrations, the stack trace
pointing at M2M fields:
TypeError: attribute name must be string, not 'bytes'

* Drop parens from user.is_authenticated

* Change Login/LogoutView to Login/LogoutView.as_view()

* Nest login.html in registration dir

* Upgrade to 2.2.26

* Upgrade to sorl-thumbnail==12.4.1

Note: thumbnail.0001_initial migration was not in my django_migrataion
table, so after this upgrade I was prompted to apply the migration, which
then errored out because the thumbnail_kvstore table already exists.

Probably related to the issue here:
https://github.com/jazzband/sorl-thumbnail/issues/458

To fix, I just manually added a row to django_migrations to indicate
that this migration was already applied.

* Upgrade to sorl-thumbnail==12.5.0

This fixes the bug on the UploadedImage admin (due to sorl thumbnail
widget compatibility)

* Upgrade all the way to sorl-thumbnail==12.7.0

* Upgrade to django-taggit==2.0.0

* Restore cors middleware (and upgrade package)